name: Docker push
run-name: "DockerPush : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if version already exist
        run: |
          json_content=$(cat package.json)
          version=$(echo "$json_content" | jq -r '.version')
          echo "Target version : $version"
          if [[ $(docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/dj-flossy:$version 2> /dev/null) != "" ]]; then
            echo -e "\e[31mVersion $version already exist"
            echo "Version $version already exist" >> $GITHUB_STEP_SUMMARY
          else
            echo -e "\e[32mBuild image version $version"
            echo "::set-output name=run_build::ys"
            echo "::set-output name=version::$version"
          fi



  Build_Push:
    runs-on: ubuntu-latest
    needs:
      - Check
    if: ${{ needs.Check.outputs.run_build == 'yes' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Echo version
        env:
          version: ${{ needs.Check.outputs.version }}
        run: echo "Build image ${{ secrets.DOCKERHUB_USERNAME }}/dj-flossy:$version"

  Test:
    runs-on: ubuntu-latest
    needs:
      - Check
    steps:
      - name: Echo all
        env:
          test: ${{ needs }}
        run: echo $test

      - name: Echo version
        env:
          version: ${{ needs.Check.outputs.version }}
        run: echo "Build image ${{ secrets.DOCKERHUB_USERNAME }}/dj-flossy:$version"